### ISSUE TITLE
Implement Selenium Automation Testing for SDX-Meican

### ISSUE THREAD

**Issue by mahidhar1g** [atlanticwave-sdx/sdx-meican#34]
Issue:
=====
We need to integrate Selenium automation testing into the SDX-Meican project to enhance its UI-level testing capabilities and ensure robustness in our software releases.

Objective:
========
The primary goal of this task is to establish a Selenium-based automation framework tailored specifically for SDX-Meican. This framework will allow us to automate the testing of critical functionalities at the UI level, improve test coverage, and streamline our testing processes.

Scope:
=====
- Framework Setup: Set up a Selenium automation framework compatible with the SDX-Meican project environment.
- Test Script Development: Develop test scripts to cover key features and user workflows of SDX-Meican.
- Integration with CI/CD: Integrate the automation tests with our continuous integration and continuous deployment pipelines to ensure tests run automatically with each build.
- Reporting and Monitoring: Implement comprehensive reporting and monitoring mechanisms to track test results and identify issues efficiently.
- Maintenance and Scalability: Ensure the automation framework is easily maintainable and scalable to accommodate future changes and additions to the SDX-Meican application.

Expected Deliverables:
=================
- Fully functional Selenium automation framework integrated into the SDX-Meican project.
- Test scripts covering essential functionalities and user scenarios.
- Integration with CI/CD pipelines for automated testing.
- Documentation detailing setup instructions, usage guidelines, and maintenance procedures.

**Comment by usmanazFIU** [comment]
I am working with @mahidhar1g on this issue. We are setting up local environment with Python and Selenium for creating a test framework and writiing some intitial test cases. We will also be creating a test case template to keep track

**Comment by usmanazFIU** [comment]
closing this issue as we have created another seperate repository for MEICAN Automation testing : https://github.com/atlanticwave-sdx/meican-testing. the issues and relevant test cases will all be on this branch
