### ISSUE TITLE
adding support for list connections

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/sdx-meican#35]
- Network operators must have the option to list connections requests made.
- MEICAN will use GET endpoint for listing connections of SDX-Controller

**Comment by usmanazFIU** [comment]
![image](https://github.com/atlanticwave-sdx/sdx-meican/assets/104851066/36b6d201-f208-459b-a674-6040bfef6773)
This is a prototype of how connection requests will be listed with the option to edit and delete them

**Comment by usmanazFIU** [comment]
UI has changed as per @italovalcy suggestion. 
![image](https://github.com/atlanticwave-sdx/sdx-meican/assets/104851066/6181bd63-dc16-471a-8bad-be724b44ad4f)

**Comment by usmanazFIU** [comment]
![image](https://github.com/atlanticwave-sdx/sdx-meican/assets/104851066/0b431c77-fd8e-4a5e-9d1e-0b9c402bf92c)

**Comment by usmanazFIU** [comment]
integration with GET /list connections endpoint from sdx-controller is remaining

**Comment by mahidhar1g** [comment]
Integration with GET /list connections endpoint from sdx-controller is completed. The below is a screenshot at the UI level.
<img width="1440" alt="list_connections" src="https://github.com/atlanticwave-sdx/sdx-meican/assets/156211533/506cd7ef-d7cf-4537-b430-eb1619b0966c">
