### ISSUE TITLE
Update MEICAN for provisioning according to specification 2.0

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/sdx-meican#50]
Update Meican UI and Request format according to data model specification 2.0

**Comment by mahidhar1g** [comment]
Post Request UI Changes

<img width="1440" alt="Meican Post Request UI 1" src="https://github.com/atlanticwave-sdx/sdx-meican/assets/156211533/8efebaf9-a3b2-4bd8-89ed-a8d45f9fe938">

<img width="1440" alt="Meican Post Request UI 2" src="https://github.com/atlanticwave-sdx/sdx-meican/assets/156211533/c54d7599-03f1-40ae-86da-7cc97d272b12">
