### ISSUE TITLE
add PATCH for l2vpns in MEICAN

### ISSUE THREAD

**Issue by usmanazFIU** [atlanticwave-sdx/sdx-meican#69]
By using the PATCH l2vpn endpoint MEICAN must support editing connections

**Comment by mahidhar1g** [comment]
<img width="1439" alt="Screenshot 2024-10-07 at 10 12 27 AM" src="https://github.com/user-attachments/assets/452de628-13ec-4c1d-97bb-c0c92f75694c">

**Comment by usmanazFIU** [comment]
@mahidhar1g 
![image](https://github.com/user-attachments/assets/a3567467-6e30-4d95-a0ec-6f505fad62bb)
empty rows are being populated

**Comment by usmanazFIU** [comment]
@congwang09 https://github.com/atlanticwave-sdx/sdx-controller/issues/333 this issue needs to be fixed

**Comment by usmanazFIU** [comment]
@congwang09 https://github.com/atlanticwave-sdx/sdx-controller/issues/334 also this

**Comment by usmanazFIU** [comment]
@congwang09 https://github.com/atlanticwave-sdx/sdx-controller/issues/336

**Comment by mahidhar1g** [comment]
Hi @congwang09,  used this post request structure to create a connection
{
    "name": "Test for new connection",
    "endpoints": [
        {
            "id": "urn:sdx:port:ampath.net:Novi03:1",
            "name": "urn:sdx:port:ampath.net:Novi03:1",
            "vlan": "any"
        },
        {
            "id": "urn:sdx:port:tenet.ac.za:Novi07:1",
            "name": "urn:sdx:port:tenet.ac.za:Novi07:1",
            "vlan": "any"
        }
    ]
}

But this is the response structure what I am seeing from the get all connection
  "99d6344a-a39c-4b41-a7f8-d865057bbe6b": {
    "99d6344a-a39c-4b41-a7f8-d865057bbe6b": {
      "description": null,
      "endpoints": [
        {
          "port_id": "urn:sdx:port:ampath.net:Novi03:1",
          "vlan": "4087"
        },
        {
          "port_id": "urn:sdx:port:ampath.net:Novi03:1",
          "vlan": "4086"
        },
        {
          "port_id": "urn:sdx:port:tenet.ac.za:Novi07:1",
          "vlan": "4087"
        },
        {
          "port_id": "urn:sdx:port:tenet.ac.za:Novi07:1",
          "vlan": "4086"
        }
      ],
      "name": "Test for new connection",
      "service_id": "99d6344a-a39c-4b41-a7f8-d865057bbe6b"
    }
  }
I don't understand why we got four endpoints, and even the vlan values are wrong. And the format is also wrong according to the specification.

**Comment by mahidhar1g** [comment]
For the above 4 endpoints problem, @italovalcy already opened the issue [337](https://github.com/atlanticwave-sdx/sdx-controller/issues/337).

After discussing this with @YufengXin and @congwang09, I learned that the other two endpoints are related to a field called provision path. Apart from that endpoint-related issue (which is a blocker), everything is complete from the MEICAN UI END.
